### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by amaleky** [jarektkaczyk/eloquence-base#18]
Please add Laravel 6.0 support

**Comment by notf0und** [comment]
I've made a pull request that updates the usage of deprecated functions but for some reason, checks are failing, so please somebody could take a look into this?

https://github.com/jarektkaczyk/eloquence-base/pull/20

**Comment by PeraMika** [comment]
I see that there is commit "_Add support Laravel 6_" from **Sep 24, 2019** (and that is the latest commit). 
I'm still worried about upgrading my project to 6 because there are a lot of reports that it is not working: **https://github.com/jarektkaczyk/eloquence/issues/251** 
(also, as @notf0und mentioned - `starts_with`/`ends_with` helper functions have been deprecated... instead `Str::startsWith`/`Str::endsWith` should be used... ).

@jarektkaczyk any help/updates on this? :)

**Comment by clouder** [comment]
[laravel/helpers](https://github.com/laravel/helpers)

`composer require laravel/helpers`

got everything working for me at the moment. Laravel v6.11.0

**Comment by thebatclaudio** [comment]
Thank you @clouder 
As @PeraMika says, I'm worried about upgrading my project to Laravel 6.
I wish we can have a new release soon, @jarektkaczyk tell me if you need help!
