### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by PeraMika** [jarektkaczyk/eloquence-base#7]
This is great package, really good and I like it (particularly **_Searchable_**), but is it still maintained?

I am asking because I plan to use this package on a project I'm currently working on (Laravel 5.6), but later I plan to upgrade to newer versions of Laravel:

- to 5.7, then to 5.8 (when it's released) and finally to 5.9 (which should be LTS if I'm not wrong)

... but I'm worried because if this package is not maintained - there may be issues when upgrading (for example, it will not work on 5.9, or some other issues may occur in the meantime... :) ).

Latest commit was on _10 Mar_, and I see some issues are still opened (without any replies/answers from maintainer(s), both on [/eloquence-base](https://github.com/jarektkaczyk/eloquence-base/issues) & [/eloquence](https://github.com/jarektkaczyk/eloquence/issues)).

**Comment by ragingdave** [comment]
Honestly, I'm trying to move completely away from it since there has been no development/communication in close to a year. In my mind that means dead package. Not to mention that I'm also beginning to notice memory leaks on long running commands where especially Mutable is used. I'll be getting out of this package ASAP and never look back. It was a great toolset, but it's dead.

**Comment by jarektkaczyk** [comment]
I'm more than happy to review and merge all PRs that fix issues or improve things.

Package that doesn't have commits might be dead or simply tested and does what it is supposed to do.

**Comment by ragingdave** [comment]
I would have to politely disagree with this conclusion as over 6 months with PR's and issues opened without a single word from the maintainer, some might conclude that a dead package. TBH I would think anyone either in development or in production during that time would just deal with the bugs and move on ASAP or just move away from it straight away. 6 months without a word, especially with a github issue specifically asking if the package was being maintained is enough to basically not trust the package anymore and to be completely frank, not to trust you for any future packages. 

I might be being a bit harsh, but as someone who started using this mainly because it had the features I needed, those 6 months made me question all the work I had done to use it in a major project, and maybe it's just me, but it's entirely unacceptable. 6 months is just too long to vanish for when a package has issues/PRs without any peep.

**Comment by jarektkaczyk** [comment]
I appreciate your feedback :+1:

**Comment by PeraMika** [comment]
Thanks for the reply, it's good to see you here :) 

This package is really good, I really like _Searchable_ (there are some "alternatives" but, in my opinion, not as good as Eloquence Searchable). 

We were worried that this package is not maintained anymore... It would be very disappointing that this package just "dies", especially when there are no as good alternatives...

Again, I'm really happy that you (the author of this package) is here! I'll keep using it!
